import fs from "fs"

export const iccplusVersion = "2.8.10";

export const bolierplate = {
  version: iccplusVersion,
  isEditModeOnAll: true,
  isPointerCursor: false,
  importedChoicesIsOpen: true,
  curVolume: 100,
  isMute: false,
  showMusicPlayer: false,
  fadeTransitionColor: "#000000FF",
  fadeTransitionTime: 0.25,
  fadeTransitionIsOn: false,
  hideBackpackBtn: 0,
  btnBackpackIsOn: 0,
  showAllAddons: 0,
  tmpRow: [],
  tmpChoice: [],
  tmpRequired: [],
  tmpScore: [],
  tmpAddon: [],
  tmpGroup: [],
  rowIdLength: 4,
  objectIdLength: 4,
  words: [],
  groups: [],
  rowDesignGroups: [],
  objectDesignGroups: [],
  objectsPerRow: "col-6",
  globalRequirements: [],
  googleFonts: [],
  customFonts: [],
  compressImageAuto: false,
  useTextEditor: true,
  useToolbarBtn: false,
  useChoiceEditBtn: true,
  hideScoresUpdated: false,
  hideChoiceDT: false,
  hideImages: false,
  preloadImages: false,
  preloadExternalImages: false,
  useVW: false,
  addPrefix: true,
  activated: [""],
  rows: [
    {
      index: 0,
      id: "row-am4e",
      title: "<p>row title</p>",
      titleText: "<p><strong>row text</strong></p>",
      debugTitle: "debug title",
      objectWidth: "col-md-3",
      image: "",
      template: 1,
      isButtonRow: false,
      buttonType: true,
      buttonId: "",
      buttonText: "Click",
      buttonRandom: false,
      buttonRandomNumber: 1,
      isResultRow: false,
      resultGroupId: "",
      isInfoRow: false,
      defaultAspectWidth: 1,
      defaultAspectHeight: 1,
      allowedChoices: 0,
      currentChoices: 0,
      rowJustify: "start",
      requireds: [],
      isEditModeOn: false,
      isRequirementOpen: false,
      objects: [
        {
          index: 0,
          id: "choice-srw0",
          title: "<p>choice title</p>",
          text: "<p>choice text</p>",
          debugTitle: "",
          image: "",
          template: 1,
          objectWidth: "",
          isActive: false,
          multipleUseVariable: 0,
          initMultipleTimesMinus: 0,
          selectedThisManyTimesProp: 0,
          requireds: [],
          addons: [],
          scores: [],
          groups: [],
          objectDesignGroups: [],
        },
      ],
      rowDesignGroups: [],
      deselectChoices: false,
    },
  ],
  pointTypes: [],
  variables: [],
  mdObjects: [],
  categories: [],
  printThis: false,
  autoSaveIsOn: false,
  autoSaveInterval: 10,
  buildAutoSaveIsOn: false,
  buildAutoSaveInterval: 10,
  tooltipDelay: 1000,
  checkDeleteRow: true,
  checkDeleteObject: false,
  checkSelectAll: false,
  defaultRowTitle: "",
  defaultRowText: "",
  defaultChoiceTitle: "",
  defaultChoiceText: "",
  defaultBeforePoint: "Cost:",
  defaultAfterPoint: "points",
  defaultBeforeReq: "Required:",
  defaultAfterReq: "",
  defaultAddonTitle: "",
  defaultAddonText: "",
  enableShortcut: true,
  orderOrReqText: "0",
  defaultOrReq: "of",
  orderSelReqText: "0",
  defaultSelReq: "choice from",
  defaultRowTemplate: 1,
  defaultRowWidth: "col-md-3",
  defaultRowJustify: "start",
  defaultRowAllowedChoices: 0,
  defaultChoiceTemplate: 1,
  defaultChoiceWidth: "",
  defaultChoiceMaxNum: 99,
  defaultAddonJustify: "start",
  defaultAddonTemplate: 1,
  defaultAddonWidth: "col-12",
  defaultUseSeperateAddon: false,
  defaultUseShowAddon: false,
  defaultUseHideAddon: false,
  defaultUseShowScore: true,
  defaultUseHideValue: false,
  defaultUseShowReq: false,
  cropperPosition: 4,
  enableSearch: true,
  backpack: [
    // {
    //   index: 0,
    //   id: "default_backpack_row",
    //   isBackpack: true,
    //   title: "Result",
    //   debugTitle: "",
    //   titleText: "",
    //   objectWidth: "col-md-3",
    //   image: "",
    //   template: 1,
    //   rowJustify: "start",
    //   isButtonRow: false,
    //   buttonType: true,
    //   buttonId: "",
    //   buttonText: "Click",
    //   buttonRandom: false,
    //   buttonRandomNumber: 1,
    //   isResultRow: true,
    //   resultGroupId: "",
    //   isInfoRow: true,
    //   defaultAspectWidth: 1,
    //   defaultAspectHeight: 1,
    //   allowedChoices: 0,
    //   currentChoices: 0,
    //   requireds: [],
    //   isEditModeOn: false,
    //   isRequirementOpen: false,
    //   objects: [],
    //   rowDesignGroups: [],
    // },
  ],
  styling: {},
};


// Export boilerplate into .json
const jsonString = JSON.stringify(bolierplate, null, 2);
fs.writeFileSync("project.json", jsonString, (err) => {
  if (err) throw err;
});